# Deploy the dev / master branches on gramener.com
deploy-gramener:
  only: [master, dev, /^dev-.*$/]
  script:
    - 'ssh ubuntu@gramener.com "
        cd /mnt/gramener/apps/v1/guide;
        git checkout -- .;
        git pull;
        export PATH=/mnt/gramener/anaconda3/bin:$PATH;
        gramex setup .;
      "'
